### ISSUE TITLE
Numeric Instructions (integer)

### ISSUE THREAD

**Issue by kevinbird61** [LuisHsu/Wasm_interpret#7]
- inn.const
- inn.eqz
- inn.eq , inn.ne, inn.lt_sx, inn.gt_sx, inn.le_sx, inn.ge_sx
- inn.clz, inn.ctz, inn.popcnt
- inn.add, inn.sub, inn.mul, inn.div_sx, inn.rem_sx
- inn.and, inn.or, inn.xor
- inn.shl, inn.shr_sx, inn_rotl, inn_rotr
- i32.wrap/i64 , i64.extend_sx/i32

**Comment by LuisHsu** [comment]
Start putting instructions into decoder.
